### ISSUE TITLE
get unwanted allele in ALT column

### ISSUE THREAD

**Issue by jiehuichen** [single-cell-genetics/cellsnp-lite#105]
Hi Xianjie,

Thanks for this great software for SNP calling.

With **--genotype** option specified, I found one of the SNP with Allele we did not want.

As the attached sheet shows, the REF is **G**, and the ALT is **T**, but the allele we want is **A**.

How could I get the information for the allele we want? Do I need to provide the custom vcf to get **A** listed in the ALT column?

Thanks a lot,

Best,
Jiehui
[cellSNP_1.cells.xlsx](https://github.com/single-cell-genetics/cellsnp-lite/files/12859027/cellSNP_1.cells.xlsx)

**Comment by hxj5** [comment]
Hi Jiehui,

Yes, you may set specific allele in REF/ALT column of custom VCF to get its information (using `-R` or `-T` option in mode 1), I assume you genotyped in mode 2 (i.e., denovo genotyping without input VCF).

Best,
Xianjie

**Comment by jiehuichen** [comment]
Many thanks.

Follow your comment, I did it with the customized VCF using -R in mode 1.

Great software!
