### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by DarioS** [single-cell-genetics/cellsnp-lite#135]
Error message is unclear.

```
/usr/bin/ld: /dski/biostat/software/htslib-1.20/cram/cram_io.c:1547: undefined reference to `libdeflate_crc32'
/usr/bin/ld: /dski/biostat/software/htslib-1.20//libhts.a(cram_io.o): in function `cram_uncompress_block':
/dski/biostat/software/htslib-1.20/cram/cram_io.c:1581: undefined reference to `libdeflate_crc32'
undefined references to `libdeflate_crc32' follow
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:445: cellsnp-lite] Error 1
make[1]: Leaving directory '/dski/biostat/software/cellsnp-lite'
make: *** [Makefile:322: all] Error 2
```

**Comment by hxj5** [comment]
Hi, it seems a compling issue related to htslib. Specifically, the `libdeflate` may be missing. You may first build "libdeflate" and then pass it to htslib, something like `./configure LDFLAGS='-L/location/of/libdeflate -Wl,-R/location/of/libdeflate'`. For details, you may check out [this similar thread](https://github.com/samtools/htslib/issues/688).

Alternatively, we highly recommend installing cellsnp-lite via [conda](https://conda.io/projects/conda/en/latest/user-guide/install/index.html) to get rid of the compiling issues. `conda install -c bioconda cellsnp-lite`

**Comment by DarioS** [comment]
Very easy with conda.
