### ISSUE TITLE
long-read scRNA-seq

### ISSUE THREAD

**Issue by Jiayi-Wang-Joey** [single-cell-genetics/cellsnp-lite#138]
Hi!

Thanks for this great work. I am wondering if cellsnp-lite can also be used on long-read scRNA-seq data?

Kind regards,
Jiayi

**Comment by hxj5** [comment]
Hi Jiayi,

Cellsnp-lite was designed for short-read data. Currently, it pileups without performing UMI collapsing, which is fine for short-read data that has a low sequencing error rate (0.5% ~ 1% as I remembered). However, the pileup result for long-read data should be less accurate if its sequencing error is high. You may look at the issue [UMI Collapsing](https://github.com/single-cell-genetics/cellsnp-lite/issues/121) for more discussion.

Best,
Xianjie

**Comment by hxj5** [comment]
If the deduplication process already accounts for PCR and sequencing errors, e.g., by collapsing all reads within a UMI to a consensus read, then it should be fine to use cellsnp-lite for pileup.

**Comment by Jiayi-Wang-Joey** [comment]
" `isoseq groupdedup` performs PCR deduplication via clustering by UMI and cell barcodes. "
Then I think it should work. Thank you very much!
