### ISSUE TITLE
Small doubt on preprocessing SNP data for mouse

### ISSUE THREAD

**Issue by mauripops** [single-cell-genetics/cellsnp-lite#139]
I am currently working on processing a vcf file for the SNPs for mice from data from the Wellcome Sanger Mouse Genome Project as listed in here: https://www.jax.org/research-and-faculty/genetic-diversity-initiative/tools-data/diversity-outbred-reference-data

Following the processing as explained for human data here:
https://github.com/single-cell-genetics/cellsnp-lite/blob/master/scripts/SNPlist_1Kgenome.sh
Resulting in the data here:
https://sourceforge.net/projects/cellsnp/files/SNPlist/

I was wondering, **do the SNPs provided above for humans contain intergenic variants?**

My endgoal is to run cellsnp-lite for demultiplexing scRNAseq reads using vireo. Should I remove the intergenic variants? Or is there a reason they should be kept?

**Comment by hxj5** [comment]
The VCF does include intergenic variants, most of which are expected to be filtered during pileup by cellsnp-lite because they are expressed/present in few reads of scRNA-seq data. However, some expressed intergenic variants (could be due to technical reasons or imperfect gene annotations, etc) could provide additional genotype information for vireo to distinguish different donors.

**Comment by mauripops** [comment]
Thank you for the explanation an the prompt reply. My issue for running cell-snp seemed to be that the vcf I was using was simply too large at 74Gb.

 As my use case, related to it being used for scRNA-seq data for further demultiplexing through vireo reducing the size of my vcf file greatly reduced the computation time of my runs. From the 74Gb initially in the vcf after removing sample data, using it to filter one of my samples resulted in 30Gb of scRNA-seq data. Removing intergenic data resulted in 64Gb of reference and 29Gb of the filtered sample. Filtering intronic data on top of the intergenic changed this to only 11Gb of reference variations and 20Gb of data in the pooled sample so. Finally another great reduction was in the filtering through the AF from the reerence left only 29Gb of the orginal 74Gb and 15Gb of the filtered scRNA-seq data. And when using all 3 filters Only 4.2Gb were left of the reference variants and 9Gb of filtered scRNA-seq data.

For my use case the last file seemed good enough as I was still able to demultiplex the samples, but for more robust results I would still keep the intronic data.

Thanks again and feel free to close the issue

**Comment by hxj5** [comment]
Thanks for your detailed feedback, it is inspiring.
