### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by AnjaliC4** [single-cell-genetics/cellsnp-lite#15]
Hi, I am working on a cluster environment, and activated conda and installed cellsnp-lite, which executes cellsnp-lite --help and shows me the options, so it got successfully installed, but when actually running this, it gives me a segmentation fault. Please help!

cellsnp-lite -s /scratch/graham_atac_analysis/merged_55_371_bam/merged_173_397.bam -b /scratch/graham_atac_analysis/merged_55_371_bam/barcodes_173_397.shuf -O /scratch/graham_atac_analysis/merged_55_371_bam/snp2/snp_chrx --minMAF 0.1 -p 22 --chrom chrX

[I::main] start time: 2021-04-01 18:16:34
[I::main] mode2: pileup 22 whole chromosomes in 3345 single cells.
[E::csp_mplp_prepare] failed to set sample names.
[E::csp_pileup_core] could not prepare csp_mplp_t structure.
Segmentation fault

**Comment by hxj5** [comment]
Hi, thanks for your feedback. Seems barcodes could be wrong. Could you show a few lines of your barcode file and check if there were duplicate barcodes?

Was the latest version (v1.2.0) of cellsnp-lite you were using? you could check with `cellsnp-lite -V`

Xianjie
