### ISSUE TITLE
Understand AD matrix

### ISSUE THREAD

**Issue by Zepeng-Mu** [single-cell-genetics/cellsnp-lite#18]
Hi,

I noticed the output sparse matrix AD.mtx contains only one value, but typically the AD filed in VCF file is a vector of two for bi-allelic loci. So I'm wondering what the number in the `mtx` file represent?

Thanks!

**Comment by hxj5** [comment]
Hi, the AD.mtx contains the allele depths of the alternative (ALT) alleles while the DP.mtx stores the sum of allele depths of the reference and alternative alleles (REF + ALT). And the OTH.mtx contains the sum of allele depths of all the alleles other than REF and ALT.

**Comment by Zepeng-Mu** [comment]
Thanks!
