### ISSUE TITLE
application in scATAC-seq data

### ISSUE THREAD

**Issue by zhijunyuu** [single-cell-genetics/cellsnp-lite#26]
Hey, 

Thanks for this nice tool!

I used the cellsnp-lite and vireo for demultiplexing some 10X Genomics single cell RNA-seq data, it worked very well. Based on the description of cellsnp-lite, I think it could also be used on scATAC data.  So I tried to use cellsnp-lite on some 10X Genomics single cell ATAC-seq data, but I did not get any information in the cellSNP.base.vcf.gz file. Do you might know what the issue is? And whether do I need to set some specific parameters for scATAC-seq data? 

Thanks in advance.

Best,
Zhijun

**Comment by KeWXiong** [comment]
> Hi Zhijun,
> 
> Thank you for your feedback. Could you share your command line? I guess the issue may be caused by the improper setting of `--UMItag` for scATAC data.
> 
> Best Xianjie

Thanks for the tool.
I used the command
`cellsnp-lite -s possorted_bam.bam  -b barcodes.tsv  -O ./cellsnp_results  -R genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf  --minMAF 0.1  --minCOUNT 20  --UMItag None  --genotype` 
to call SNV from single-cell ATAC-seq data. There is no error during the running. However, most of the genotypes are valued -1. Are there any mistakes?

**Comment by hxj5** [comment]
Hi, I don't know what genotype "-1" means, could you give one example?

**Comment by KeWXiong** [comment]
> Hi, I don't know what genotype "-1" means, could you give one example?

It means that no SNP information is obtained for almost all sites, similar to NA. I've tried hg19 and hg38, but neither of them works.

**Comment by hxj5** [comment]
could you share some SNPs in the output file `cellSNP.cells.vcf.gz` (just a few columns are fine, if you have many cells)? You may also want to look at issue #44 to double check whether the input barcodes are in the right format.
