### ISSUE TITLE
definition of REF and ALT in mode 2

### ISSUE THREAD

**Issue by bobermayer** [single-cell-genetics/cellsnp-lite#28]
Hi,

I noticed that in mode 2 (with `--genotype`) the definition of `REF` and `ALT` is not what I expected. it looks like `REF` is the major and `ALT` the minor allele, such that the overall allele fraction (ratio of row sums of AD by row sums of DP) is always < 0.5. however, neither is necessarily identical to the actual (genomic) reference. this can cause confusion downstream, e.g., when comparing with lists of SNPs from other sources (where I think `REF` is always the reference allele). is this the intended behavior, and can it be changed?
I'm using `cellsnp-lite v1.2.0`

thanks!

**Comment by hxj5** [comment]
**Update**: since v1.2.2,  we have the `-f` or `--refseq` option for this issue.
