### ISSUE TITLE
running mode 2 failed

### ISSUE THREAD

**Issue by semir2** [single-cell-genetics/cellsnp-lite#3]
Thank you for your great tools with cellsnp-lite. I got  an error with running mode 2 failed, and i do not known and no usefull information.

> [E::pileup_regions] could not parse name for chrom 21.
[I::pileup_regions][Thread-18] has pileup-ed in total 212 SNPs for chrom 19
[I::pileup_regions][Thread-17] has pileup-ed in total 220 SNPs for chrom 18
[I::pileup_regions][Thread-15] has pileup-ed in total 131 SNPs for chrom 16
[I::pileup_regions][Thread-14] has pileup-ed in total 216 SNPs for chrom 15
[I::pileup_regions][Thread-12] has pileup-ed in total 223 SNPs for chrom 13
[I::pileup_regions][Thread-13] has pileup-ed in total 235 SNPs for chrom 14
[I::pileup_regions][Thread-7] has pileup-ed in total 377 SNPs for chrom 8
[I::pileup_regions][Thread-16] has pileup-ed in total 388 SNPs for chrom 17
[I::pileup_regions][Thread-11] has pileup-ed in total 251 SNPs for chrom 12
[I::pileup_regions][Thread-9] has pileup-ed in total 252 SNPs for chrom 10
[I::pileup_regions][Thread-8] has pileup-ed in total 271 SNPs for chrom 9
[I::pileup_regions][Thread-3] has pileup-ed in total 366 SNPs for chrom 4
[I::pileup_regions][Thread-5] has pileup-ed in total 317 SNPs for chrom 6
[I::pileup_regions][Thread-2] has pileup-ed in total 305 SNPs for chrom 3
[I::pileup_regions][Thread-10] has pileup-ed in total 669 SNPs for chrom 11
[I::pileup_regions][Thread-1] has pileup-ed in total 480 SNPs for chrom 2
[I::pileup_regions][Thread-0] has pileup-ed in total 461 SNPs for chrom 1
[I::pileup_regions][Thread-6] has pileup-ed in total 535 SNPs for chrom 7
[I::pileup_regions][Thread-4] has pileup-ed in total 381 SNPs for chrom 5
[E::main] running mode 2 failed.
[E::main] Quiting...
[I::main] end time: 2020-11-04 20:44:23
[I::main] time spent: 81957 seconds.

Yours

**Comment by semir2** [comment]
And my cmd as follows
`cellsnp-lite -s 10x_possorted_genome_bam.bam -b barcodes.tsv -O outdir -p 22 --minMAF 0.1 --minCOUNT 100 --gzip`

The bam was from cellranger with single cell RNA case.

**Comment by huangyh09** [comment]
For mode2, by default it runs on chr1 to 22 on human. For mouse, you need to specify it to 1,2,...,19 (replace the ellipsis).

On the other hand, if it is lab straint with genotype available, e.g., from the [mouse genome project](https://www.sanger.ac.uk/data/mouse-genomes-project/)  (ftp://ftp-mouse.sanger.ac.uk/current_snps), you can also run mode 1.

Yuanhua

**Comment by alyamahmoud** [comment]
Hi there! thanks for a great tool. 
I am not sure what 'replace the ellipsis' mean. Would you please elaborate on that? 
Thank you

**Comment by PietroD** [comment]
Continuing here from [Issue 34](https://github.com/single-cell-genetics/cellsnp-lite/issues/34#issue-1067852053).
Looking at my bam file, it looks like the chromosome notation is already like default (i.e. chr1 ... chr2...).
Do I have to change it to 1,2,...19?

One possible problem is that my bam does not contain a header. 
It is the output of `cellranger count 4.0`.
Do you have suggestions?
