### ISSUE TITLE
[E::csp_pileup] could not parse name for chrom 20

### ISSUE THREAD

**Issue by PietroD** [single-cell-genetics/cellsnp-lite#34]
Hi, 
thanks for the tools.
I am getting this error when trying mode 2a.

My command:

`cellsnp-lite -s possorted_genome_bam.bam -b filtered_feature_bc_matrix/barcodes.tsv.gz -O cellsnp_out/ -p 22 --minMAF 0.1 --minCOUNT 100 --gzip`

Output:

`[I::main] start time: 2021-11-30 17:41:00`
`[W::check_args] Max depth set to maximum value (2147483647)`
`[I::main] mode 2a: pileup 22 whole chromosomes in 5219 single cells.`
`[E::csp_pileup] could not parse name for chrom 20.`
`[E::main] running mode 2a failed.`
`[E::main] Quiting...`
`[I::main] end time: 2021-11-30 17:41:00`
`[I::main] time spent: 0 seconds.`

I am working with cellsnp-lite 1.2.2 (htslib 1.12)

Thanks

**Comment by hxj5** [comment]
Hi, thanks for your feedback. Is this a dataset for mouse? If yes, please refer to [issue 3](https://github.com/single-cell-genetics/cellsnp-lite/issues/3).
