### ISSUE TITLE
Empty o/p matrix files

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [single-cell-genetics/cellsnp-lite#36]
Hi @hxj5 
We have scATAC-seq data from 3 pooled samples, the coverage is 980 raw read pairs per cell (shallow sequencing)

Mode 1a
`
cellsnp-lite -b /home/ubuntu/outs/filtered_feature_bc_matrix/barcodes.tsv -s /home/ubuntu/outs/atac_possorted_bam.bam -R genome1K.phase3.SNP_AF5e4.chr1toX.hg38.vcf.gz -O cellsnp-PM_002 -p 20 --minMAF 0.1 --minCOUNT 20 --gzip`

 The output matrix files of cellSNP-lite are empty
```

%%MatrixMarket matrix coordinate integer general
%
0	3098	0
```

Please let me know what parameter combination would yield result.
Thank you!

Best,
Parul

**Comment by hxj5** [comment]
Hi Parul,

Thanks for the feedback. You may want to add `--UMItag None` option for scATAC data, as discussed in [issue #26](https://github.com/single-cell-genetics/cellsnp-lite/issues/26).

Best,
Xianjie

**Comment by Parul-Kudtarkar** [comment]
Thanks @hxj5 that's helpful
