### ISSUE TITLE
lose cellSNP.cells.vcf.gz file

### ISSUE THREAD

**Issue by penglbio** [single-cell-genetics/cellsnp-lite#4]
When I test the software  cellSNP-lite and cellSNP, I find the output files of cellSNP-lite have no cellSNP.cells.vcf.gz file. The following is my command:
cellsnp-lite -s demux.B.lite.bam -b demux.B.barcodes.400.tsv -O test1 -p 22 --minMAF 0.1 --minCOUNT 100 --gzip

cellSNP.base.vcf.gz
 cellSNP.samples.tsv
cellSNP.tag.AD.mtx
 cellSNP.tag.DP.mtx
 cellSNP.tag.OTH.mtx

cellSNP -s demux.B.lite.bam -b demux.B.barcodes.400.tsv -O test2 -p 22 --minMAF 0.1 --minCOUNT 100 

6 output files:
cellSNP.base.vcf.gz
cellSNP.cells.vcf.gz
 cellSNP.samples.tsv
cellSNP.tag.AD.mtx
 cellSNP.tag.DP.mtx
 cellSNP.tag.OTH.mtx

**Comment by hxj5** [comment]
Hi, you could add `--genotype` option for cellsnp-lite so that it will output `cellSNP.cells.vcf.gz`

**Comment by huangyh09** [comment]
BTW, if you are using vireo for your next step, you can use `-C` for the folder, instead of `-c` for `cellSNP.cells.vcf.gz`, as the folder containing the sparse matrices have equivalent information.
