### ISSUE TITLE
Issue with reference for cellsnp-lite

### ISSUE THREAD

**Issue by haigdjambazian** [single-cell-genetics/cellsnp-lite#43]
I get this error on running cellsnp-lite:
`[I::main] start time: 2022-05-25 08:01:24
[W::check_args] Max depth set to maximum value (2147483647)
[I::main] mode 2a: pileup 22 whole chromosomes in 737280 single cells.
[E::csp_pileup] could not parse name for chrom 1.
[E::main] running mode 2a failed.
`
Is the tool expecting the reference to be named a certain way?
This is the format of my reference header:
`>OVEO01000019 1 Plasmodiophora brassicae genome assembly, contig: contig_19_no3tel, whole genome shotgun sequence`
Thanks in advance.

**Comment by hxj5** [comment]
Hi, as you were running mode 2a, the tool expects the input chromosome names (specified by `--chrom`) to match the names in bam header (you may check with `samtools view -h <bam>`). The default value for `--chrom` is 1,2,...,22, you may change it based on your reference file or bam file.
