### ISSUE TITLE
Filtering cells before or after cellsnp-lite

### ISSUE THREAD

**Issue by haigdjambazian** [single-cell-genetics/cellsnp-lite#68]
If I wanted to only consider real cells is there a way to filter cells that have too low read counts?  I see how I could filter the input reads or bam myself before cellsnp-lite but I was wondering what you think.  Can vireo filter cells out before running?
Thanks.

**Comment by hxj5** [comment]
Hi, cellsnp-lite or vireo can not filter cells with low read counts. This task is more like "cell calling". You may use cell barcodes stored in cellranger folder `filtered_gene_bc_matrices`, or filter cells based on the UMI/read counts generated from the bam file.
