### ISSUE TITLE
Duplicate barcodes error?

### ISSUE THREAD

**Issue by terencewtli** [single-cell-genetics/cellsnp-lite#80]
Hi,

Thanks for providing this tool - I've had success with it for 10X bam files. However, for another dataset, I'm encountering a duplicate barcodes issue: 
```
[W::csp_mplp_prepare] duplicate barcodes or sample IDs.
[E::csp_mplp_prepare] failed to set sample names.
```
I'm using data from SHARE-seq, which looks like:

```
A00438:1038:HHGGKDRX2:2:2172:32045:23703_TTCCTGCT,CCTATTGA,TGACCACT,SS-PKR-126_CCCTAACCCT       272     chr1    10108   0       20S30M  *       0       0       CCGGAGATGTGTATAAGAGACAGCCCTAACCCTAACCCTAACCCTAACCC   FFFFFF,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF      NH:i:6  HI:i:3  AS:i:27 nM:i:1  MD:Z:2A27       NM:i:1  CB:Z:TTCCTGCTCCTATTGATGACCACT
```
The command I'm using is:
```
 time cellsnp-lite -s $BAM -b $BARCODES \
  -O $OUT -R ${VCF} --minMAF 0.1 --minCOUNT 20 --gzip
```
I've verified that the barcodes supplied to cellsnp-lite are unique, so I am a bit lost on why this error is occurring. Does it have something to do with the barcodes existing in the read names?

**Comment by hxj5** [comment]
Hi, thanks for the feedback. Seems the program failed when checking barcodes. Although you may have verified that the barcodes are unique, could you share the barcode file here for double check?

**Comment by terencewtli** [comment]
Hi,

Sorry for the late response! This is embarrassing, but it turns out that there were duplicate barcodes that I didn't remove properly. Once I fixed that, it's working now. Thank you!
