### ISSUE TITLE
Barcodes File Clarification

### ISSUE THREAD

**Issue by DarioS** [single-cell-genetics/cellsnp-lite#81]
In the documentation, I see `-b $BARCODE` but it doesn't explain what is required file format nor where to download it for Chromium.

**Comment by hxj5** [comment]
Hi, `-b` requires a file listing cell barcodes, one barcode per line. You may use the `barcodes.tsv` file in the output directory of 10x CellRanger, `outs/filtered_gene_bc_matrices/`.

**Comment by DarioS** [comment]
That's useful to know. Could you add it to the user manual so that it also helps others with the same confusion?

**Comment by hxj5** [comment]
yes sure, thanks for your suggestion.
