### ISSUE TITLE
Handling haploid cells

### ISSUE THREAD

**Issue by haigdjambazian** [single-cell-genetics/cellsnp-lite#87]
Hi, the species I am studying is haploid: Plasmodiophora brassicae (size: 24Mb) we captured single spores.

Is there an option with cellsnp-lite to have it only make calls based on a haploid organism? I think heterozygous snps don't really make sense unless we have a doublet.

**Comment by hxj5** [comment]
Hi, cellsnp-lite was designed for diploid data. For the moment, you may have to (post-hoc) filter the heterozygous SNPs.
