### ISSUE TITLE
How to use cellsnp-lite

### ISSUE THREAD

**Issue by DaliBAmor** [single-cell-genetics/cellsnp-lite#89]
Hello , I want to thank you for this fantastic tool and i would be really greateful if you can answer my question
-Question 1: could we use cellsnp-lite on Human BAM file generated by cellranger count ( the fastq file are genetaed by 10* genomics using the manifacture protocole)
Question 2 : could you give as an example of a command line inorder to know how to use cellsnp-lite like you did here in the case of cellsnp ( # 10x sample with cell barcodes
cellSNP -s $BAM -b $BARCODE -O $OUT_DIR -p 22 --minMAF 0.1 --minCOUNT 100)
Question3 : what's the tool that you created for indels detection please 

thank you in advance 
I hope you will answer my questions

**Comment by hxj5** [comment]
Hi, thanks for your interest in cellsnp-lite.
Q1: yes, cellsnp-lite could be applied on 10x data generated by cellranger count.
Q2: `cellsnp-lite -s $BAM -b $BARCODE -O $OUT_DIR -p 22 --minMAF 0.1 --minCOUNT 100 --gzip`. For details, you may look into the [manual](https://cellsnp-lite.readthedocs.io/en/latest/manual.html#quick-usage).
Q3: the tool for indel detection is still under development, we may try to release the alpha version.
