### ISSUE TITLE
Filter SNPs by minMAF after running cellsnp-lite 

### ISSUE THREAD

**Issue by flde** [single-cell-genetics/cellsnp-lite#90]
Hello all, 

I have clinical samples of mixed host/donor cells. I found that minMAF might be optimized for each patient. Thanks to your help I understand now that minMAF filters the SNP list based on the MAF diverged from the single cell reads (#77). 

To generate SNP lists with different minMAF I would need to run cellsnp-lite iteratively which takes a lot of time/resources. Do I understand correctly that I could instead filter the cellsnp-lite result vcf.gz file with bcftools at different minMAF threshold before passing it to vireo? 

Many thanks again for your help! 

Best wishes, 
Florian

**Comment by hxj5** [comment]
Hi Florian,

Thanks for the question. For typical task of donor deconvolution, such as on scRNA-seq data of mixed cells from multiple patients, you only need to perform SNP calling & genotyping once before passing the genotypes to vireo. Please correct me if I misunderstood your question.

Best,
Xianjie

**Comment by flde** [comment]
Hi @hxj5, 

My apologies. What I want to test is different minMAF threshold e.g. 10%, 5%, 1%. But I want to avoid running cellsnp for every threshold. So, could I run cellsnp once with minMAF 1% and then filter the result cellSNP.base.vcf.gz by 10% and 5% to achieve the same result? 

For filtering the result file, I would use bcftools view -q 0.05:minor cellSNP.base.vcf.gz and pass this to vireon. 

Best wishes, 
Florian

**Comment by hxj5** [comment]
yes, you could post-filter SNPs in the way as you mentioned (i.e., run cellsnp with minMAF 1% and then post-filter with minMAF 5%, 10%). Thanks for the clarification. 

I have little experience about `bcftools view -q`. Basically, to filter SNPs outputted by cellsnp, based on minMAF threshold, you could test `min(AD/DP, (DP-AD)/DP) < minMAF_threshold` on the `cellSNP.base.vcf` file and update the three matrices accordingly.

**Comment by hxj5** [comment]
Hi Florian,

I have uploaded a demo R script `csp_utils.R` to the [scripts/utils](https://github.com/single-cell-genetics/cellsnp-lite/tree/master/scripts/utils) dir. You may download the script and then call the `update_cellsnp_matrices` function to update the three sparse matrices. The usage of the function should be straightforward, although it has not been thoroughly tested. 

Best,
Xianjie

**Comment by flde** [comment]
Hi Xianjie, 

That is so very kind of you! I think having such an option is very helpful to optimize cellsnp downstream. 

In my case I have samples of only host and mixed host/donor cells. So, I run cellsnp+vireo on the pooled data and then split it again. So, I can use the host only samples to estimate the sensitivity/specificity. 

The challenge is that the ratio of host/donor cells varies and also some host/donor are genetically closer related than others. I think in such cases one could optimize minMAF a bit. Having a tool to split the SNPs by minMAF is a great enhancement from my point of few. 

Again, many thanks and all the best, 
Florian

**Comment by hxj5** [comment]
Hi Florian,

It should be fine, provided that the number of filtered cells is limited (so that there would be little impact on the SNP calling & genotyping).

Best,
Xianjie
